// TTCN-3 Grammar
// ==============
//
// This Grammar is still very much work in progress.
//


//
// Modules, module defintions and declarations.
// --------------------------------------------
//

Module = "module" Name [Language] "{" { Decl ";" } "}" [With] ";".

Decl = Altstep
     | AltstepType
     | Class
     | Component
     | Configuration
     | Constructor
     | Control
     | Destructor
     | Enum
     | Friend
     | Function
     | FunctionType
     | Group
     | Import
     | List
     | Map
     | Port
     | Signature
     | Struct
     | SubType
     | Template
     | Testcase
     | TestcaseType
     | VarDecl
     .

Group = [Visibility] "group" Name "{" { Decl ";" } "}" [With].

Friend = [Visibility] "friend" "module" Refs [With].

Import = [Visibility] "import" "from" Ref ["->" Name] ("all" [ExceptSpec] | ImportSpec) [With].

ExceptSpec = "except" "{" { ExceptStmt ";" } "}".
ExceptStmt = ImportKind (Refs|"all")
           | "group"    (Refs|"all")
           .

ImportSpec = "{" { ImportStmt ";" } "}".
ImportStmt = ImportKind (Refs|"all" ["except" Refs])
           | "group"    {Ref [ExceptSpec]}
           .

ImportKind
    = "altstep"
    | "const"
    | "function"
    | "import"
    | "modulepar"
    | "signature"
    | "template"
    | "testcase"
    | "type"
    .

// Signature declaration
Signature = [Visibility] "signature" Name [FormalTypePars] FormalPars [Return] ["noblock"] [Exception] [With].

// Component declaration
Component = [Visibility] "type" "component" Name [FormalTypePars][Extends] Block [With].

// Port declaration
Port = [Visibility] "type" "port" Name PortKind {PortSpec} "{" {PortAttribute ";"} "}" [With].

PortKind = "message"
         | "procedure"
	 | "stream"
	 .

PortSpec = "realtime"
         | "map" "to" Refs
	 | "connect" "to" Refs
	 .

PortAttribute = "map"   "param" FormalPars
              | "unmap" "param" FormalPars
              | "address" Ref [PortTranslation]
              | ("in"|"out"|"inout") {PortElement ","}
              .

PortElement = Ref [PortTranslation].
PortTranslation =("from"|"to") Ref "with" Ref "(" ")".

// User defined types

SubType = [Visibility] "type" Ref Name [FormalTypePars] {ArrayDef} ["(" Exprs ")"] [With].

Struct = [Visibility] "type" StructKind Name [FormalTypePars] "{" { StructMember "," } "}" [With].

StructKind = "record" | "set" | "union".

StructMember = ["@default"] NestedType Name {ArrayDef} ["(" Exprs ")"].

List = [Visibility] "type" ListKind ["length" "(" Expr ")"] "of" NestedType Name [With].
ListKind = "record" | "set".

Enum = [Visibility] "type" "enumerated" Name "{" { EnumLabel "," } "}" [With].

EnumLabel = Name ["(" Exprs ")"].

Map = [Visibility] "type" "map" "from" Ref "to" Ref Name [With].

Class = [Visibility] "type" ["external"] "class" {modifier} Name [Extends] {ConfigSpec} "{" { Decl ";" } "}" ["finally" Block] [With].

Constructor = [Visibility] "create" FormalPars ["external" FormalPars] [":" Ref "(" Exprs ")" ] [Block] .

Control = "control" Block.

Destructor = "finally" Block.

TestcaseType = [Visibility] "type" "testcase" Name FormalPars {ConfigSpec} [With].

FunctionType = [Visibility] "type" "function" {modifier} Name FormalPars {ConfigSpec} [Return] [With].

AltstepType = [Visibility] "type" "altstep" {modifier} ["interleave"] Name FormalPars {ConfigSpec} [With].


// Variable declaration and module parameters.

VarDecl = [Visibility] ("const"|"var"|"modulepar") [NestedTemplate] {modifier} Ref Declarator { "," Declarator} [With].

TimerDecl = "timer" Declarator { "," Declarator} [With].
PortDecl = "port" Ref Declarator { "," Declarator} [With].

// Template declaration
Template = [Visibility] "template" [ "(" TemplateRestriction ")"] {modifier} Ref Name [FormalPars] ["modifies" Ref] ":=" Expr [With].

// Testcase declaration
Testcase = [Visibility] "testcase" Name FormalPars {ConfigSpec} Block.

// Function declaration
Function = [Visibility] ["external"] "function" {modifier} Name FormalPars {ConfigSpec} [Return] [Exception] [Block] [With].

// Configuration declaration
Configuration = [Visibility] "configuration" Name FormalPars {ConfigSpec} Block [With].

// Altstep declaration
Altstep = [Visibility] "altstep" {modifier} ["interleave"] Name FormalPars {ConfigSpec} Block [With].

//
// Statements
// ----------
//

Stmt
    = AltStmt
    | Block
    | DoStmt
    | Expr
    | ForStmt
    | GotoStmt
    | GuardStmt
    | IfStmt
    | LabelStmt
    | PortDecl
    | ReturnStmt
    | SelectStmt
    | Template
    | TimerDecl
    | VarDecl
    | WhileStmt
    .

IfStmt     = "if" "(" [(AssignStmt|VarDecl) ";"] Expr ")" Block {"else" "if" "(" Expr ")" Block} ["else" Block].
SelectStmt = "select" ["union"|"class"] "(" Expr ")" "{" { "case" ("else"|"(" Expr ")") Block } "}".
ForStmt    = "for" "(" (AssignStmt|VarDecl) ("in" Ref|";" Expr";" AssignStmt) ")" Block.
WhileStmt  = "while" "(" Expr ")" Block.
DoStmt     = "do" Block "while" "(" Expr ")".
GotoStmt   = "goto" Ref.
LabelStmt  = "label" Name.
ReturnStmt = "return" [Expr].
AltStmt    = ("alt"|"interleave") {modifier} Block.
AssignStmt = Ref ":=" Expr.
GuardStmt  = "[" [Expr] "]" Stmt.


Block = BasicBlock ["catch" "(" Ref Name ")" BasicBlock] ["finally" BasicBlock].

BasicBlock = "{" { Stmt ";" } "}".

//
// Expressions
// -----------
//

Exprs = {Expr "," }.

Expr = PrimaryExpr
     | Literal
     | UnaryExpr
     | BinaryExpr
     .

PrimaryExpr = Ref { "." Ref | "[" Expr "]" | "(" Exprs ")" }.

Literal = integer
        | float
	| string
	| bitstring
	| "true" | "false"
	| "none" | "pass" | "inconc" | "fail" | "error"
	| "-"
	| "?"
	| "*"
	| "omit"
	| "not_a_number"
	| "null"
	.

UnaryExpr = "!" Expr
          | "+" Expr
	  | "-" Expr
          | "not" Expr
          | "not4b" Expr
	  .

BinaryExpr = Expr ":=" Expr
           | Expr ":" Expr
           | Expr "=>" Expr
           | Expr ".." Expr
           | Expr "of" Expr
           | Expr "or" Expr
           | Expr "xor" Expr
           | Expr "and" Expr
           | Expr "==" Expr
           | Expr "!=" Expr
           | Expr "<" Expr
           | Expr "<=" Expr
           | Expr ">" Expr
           | Expr ">=" Expr
           | Expr "<@" Expr
           | Expr "<<" Expr
           | Expr ">>" Expr
           | Expr "@>" Expr
           | Expr "or4b" Expr
           | Expr "xor4b" Expr
           | Expr "and4b" Expr
           | Expr "+" Expr
           | Expr "-" Expr
           | Expr "&" Expr
           | Expr "*" Expr
           | Expr "/" Expr
           | Expr "rem" Expr
           | Expr "mod" Expr
           | Expr "::" Expr
	   .

Ref = identifier [TypePars]
    | "address"
    | "all" "component"
    | "all" "port"
    | "all" "timer"
    | "any"
    | "any" "component"
    | "any" "port"
    | "any" "timer"
    | "map"
    | "mtc"
    | "self"
    | "system"
    | "this"
    | "timer"
    | "universal" "charstring"
    | "unmap"
    .

TypePars = "<" { TypePar "," } ">" .

TypePar = [ Name ":=" ] NestedType .

//
// Fragments, building blocks and helpers
// --------------------------------------
//

With = "with" "{" {WithStmt ";"} "}".

WithStmt =  ("encode"|"variant"|"display"|"extension"|"optional") ["override"|"@local"] ["(" WithQualifier [","] ")"] string.

WithQualifier
    = Ref
    | "[" Expr "]"
    | WithKind [ "except" "{" Refs "}" ]
    .

WithKind
    = "altstep"
    | "const"
    | "function"
    | "group"
    | "modulepar"
    | "signature"
    | "template"
    | "testcase"
    | "type"
    .

// Refs must not be empty
Refs = {Ref ","} .

Extends = "extends" Refs.
Language = "language" {string ","}.
Return = "return" [NestedTemplate] Ref {ArrayDef} .

ConfigSpec
    = "runs" "on" Ref
    | "system" Ref
    | "mtc" Ref
    | "port" Ref
    | "execute" "on" Ref
    .

Exception = "exception" "(" Refs ")".


Visibility = "private"|"public"|"friend".

Name = identifier.

FormalTypePars = "<" FormalTypePar {"," FormalTypePar} [","] ">".
FormalTypePar = ["in"] ("type"|"signature"|Ref) Declarator.

FormalPars = "(" FormalPar {"," FormalPar} [","] ")".
FormalPar = ("in"|"out"|"inout") Ref Declarator.

Declarator = Name {ArrayDef} [":=" Expr].

ArrayDef = "[" Expr "]".

TemplateRestriction = "omit" | "value" | "present".


NestedTemplate
    = "template"
    | "template" "(" TemplateRestriction ")"
    | TemplateRestriction
    .


NestedType
    = Ref
    | NestedStruct
    | NestedList
    | NestedEnum
    .

NestedStruct = ("record"|"set"|"union") "{" { StructMember "," } "}".
NestedList = ("record"|"set") ["length" "(" Expr ")"] "of" NestedType.
NestedEnum = "enumerated" "{" {EnumLabel "," } "}".

 identifier = .
 modifier = .
 integer = .
 float = .
 string = .
 bitstring = .
